### ISSUE TITLE
(production) ND Spotlight crash, error: Cannot read properties of undefined (reading 'label')

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/public-dashboard#646]
**Describe the bug**
If you load the [ND Spotlight](https://dashboard.docr.nd.gov/us-nd),  it loads normally then begins its auto-rotation through each section of the site. If you let it be, when it tries to auto-rotate to Parole the entire app crashes and only shows this:
![image](https://github.com/Recidiviz/public-dashboard/assets/59526/a1cda259-ca28-4169-a2f9-295314224392)

The console log includes the following stack trace (full console log attached):

```
instrument.js:108 TypeError: Cannot read properties of undefined (reading 'label')
    at lc (Region.tsx:53:11)
    at na (react-dom.production.min.js:157:137)
    at Vu (react-dom.production.min.js:267:460)
    at ks (react-dom.production.min.js:250:347)
    at xs (react-dom.production.min.js:250:278)
    at ws (react-dom.production.min.js:250:138)
    at hs (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Vi (react-dom.production.min.js:122:325)
    at Hi (react-dom.production.min.js:123:61)
    at Wi (react-dom.production.min.js:122:428)
    at Ms (react-dom.production.min.js:263:32)
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Vi (react-dom.production.min.js:122:325)
    at js (react-dom.production.min.js:261:308)
    at react-dom.production.min.js:261:215
    at B (scheduler.production.min.js:16:224)
    at x.port1.onmessage (scheduler.production.min.js:12:346)
```

[dashboard.docr.nd.gov-1712944856081.log](https://github.com/Recidiviz/public-dashboard/files/14961943/dashboard.docr.nd.gov-1712944856081.log)

**To Reproduce**
1. Go to https://dashboard.docr.nd.gov/
2. Click nothing, do nothing. Wait for it to rotate to **Parole**. (Alternatively, try to click **Parole** in the nav.)
3. See error

**Expected behavior**
Expected to see the Parole preview on the home page, or the Parole page to load when I tried navigating there directly.

**Screenshots**
See attached screenshot above.

**Desktop (please complete the following information):**
Google Chrome	123.0.6312.94 (Official Build) (64-bit) 
Revision	15e613c6705715afe59147024b37b926e7cabb75-refs/branch-heads/6312@{#734}
Platform	15786.41.0 (Official Build) stable-channel zork
Firmware Version	Google_Morphius.13434.356.0
Customization ID	morphius
ARC	11617647 SDK Version: 33
JavaScript	V8 12.3.219.15
User Agent	Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Smartphone (please complete the following information):**
Reproduced on Android 14, Pixel 8, in Chrome 123.0.6312.100

**Comment by cawarren** [comment]
@lilidworkin Serena mentioned you might be the right person to tag / notify of this

**Comment by macfarlandian** [comment]
this was caused by a data platform issue that resulted in some data export failures. a successful export earlier this afternoon seems to have resolved it!
